workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 60
    environment:
      groups:
        - google_play
      vars:
        PACKAGE_NAME: "com.mixtapeoficialmx.app"
      node: 18
      java: 17
    scripts:
      - name: Install npm dependencies
        script: |
          npm install
      - name: Install Expo CLI
        script: |
          npm install -g expo-cli
      - name: Prebuild native code
        script: |
          npx expo prebuild --platform android --clean
      - name: Build Android APK
        script: |
          cd android
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/**/*.apk